version: "3.8"

name: hackathon-idp

services:
  hackathon-db:
    image: postgres:latest
    container_name: hackathon-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"

volumes:
  db_data:
