version: "3.8"

name: hackathon-idp

services:
  hackathon-db:
    image: postgres:latest
    container_name: hackathon-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data:
