version: "3.8"

name: hackathon-idp

services:
  hackathon-db:
    image: postgres:latest
    container_name: hackathon-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"

  backend:
    image: ghcr.io/hackathon-individual-development-plan/backend:latest
    container_name: backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --no-input --username admin --email admin@example.com || true &&
             python manage.py collectstatic --no-input --clear &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - backend_static:/app/static/
    depends_on:
      - hackathon-db

  frontend:
    image: ghcr.io/hackathon-individual-development-plan/frontend:latest
    container_name: frontend
    volumes:
      - frontend_static:/app/build

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - /etc/letsencrypt/live/${NGINX_SERVER_NAME}/privkey.pem:/app/ssl/privkey.pem
      - /etc/letsencrypt/live/${NGINX_SERVER_NAME}/fullchain.pem:/app/ssl/fullchain.pem
      - backend_static:/var/html/static
      - frontend_static:/var/html/frontend
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  backend_static:
  frontend_static:
