# Generated by Django 5.0.1 on 2024-01-25 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="goal_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="goal",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal_comment",
                to="idps.goalforidp",
                verbose_name="Комментарий",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
            preserve_default=False,
        ),
    ]
