# Generated by Django 5.0.1 on 2024-01-29 05:09

from django.db import migrations, models

import apps.api.v1.validators


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="deadline",
            field=models.DateTimeField(
                db_index=True,
                validators=[apps.api.v1.validators.deadline_validator],
                verbose_name="Дата дедлайна",
            ),
        ),
    ]
