# Generated by Django 5.0.1 on 2024-01-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goaltask",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals_tasks",
                to="idps.goal",
                verbose_name="Цель",
            ),
        ),
        migrations.AlterField(
            model_name="goaltask",
            name="tasks",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals_tasks",
                to="idps.task",
                verbose_name="Задачи",
            ),
        ),
    ]
