# Generated by Django 5.0.1 on 2024-01-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0002_rename_goalforidp_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("In progress", "В работе"),
                    ("Work done", "Выполнен"),
                    ("Not done", "Не выполнен"),
                ],
                default="In progress",
                max_length=11,
                verbose_name="Статус Цели",
            ),
        ),
        migrations.AlterField(
            model_name="idp",
            name="status",
            field=models.CharField(
                choices=[
                    ("In progress", "В работе"),
                    ("Work done", "Выполнен"),
                    ("Not done", "Не выполнен"),
                ],
                default="In progress",
                max_length=11,
                verbose_name="Статус ИПР",
            ),
        ),
    ]
