# Generated by Django 5.0.1 on 2024-01-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "idps",
            "0002_remove_comment_goal_id_remove_comment_user_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalforidp",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="idp",
            name="goals",
        ),
        migrations.RemoveField(
            model_name="goaltask",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="goaltask",
            name="tasks",
        ),
        migrations.AddField(
            model_name="goalforidp",
            name="description",
            field=models.TextField(
                default="lkjlk", verbose_name="Описание Цели"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goalforidp",
            name="tasks",
            field=models.ManyToManyField(
                related_name="goals", to="idps.task", verbose_name="Задачи"
            ),
        ),
        migrations.AddField(
            model_name="goalforidp",
            name="title",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Название Цели"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal_comment",
                to="idps.goalforidp",
                verbose_name="Цель",
            ),
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
        migrations.DeleteModel(
            name="GoalTask",
        ),
    ]
