# Generated by Django 5.0.1 on 2024-01-21 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0002_alter_goaltask_options_alter_goaltask_tasks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("text", "created_at"),
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AlterField(
            model_name="goaltask",
            name="tasks",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="idps.task",
                verbose_name="Задачи",
            ),
        ),
        migrations.CreateModel(
            name="GoalForIdp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In progress", "В работе"),
                            ("Work done", "Выполнен"),
                            ("Not done", "Не выполнен"),
                            ("Empty", "Отсутствует"),
                        ],
                        default="In progress",
                        max_length=11,
                        verbose_name="Статус Цели",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        db_index=True, verbose_name="Дата дедлайна"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата закрытия цели",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idp_goals",
                        to="idps.goal",
                        verbose_name="Цель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель ИПР",
                "verbose_name_plural": "Цели для ИПР",
                "ordering": ("created_at", "idp__title", "status", "deadline"),
            },
        ),
        migrations.CreateModel(
            name="Idp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=20, verbose_name="Наименование ИПР"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In progress", "В работе"),
                            ("Work done", "Выполнен"),
                            ("Not done", "Не выполнен"),
                            ("Empty", "Отсутствует"),
                        ],
                        default="In progress",
                        max_length=11,
                        verbose_name="Статус ИПР",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата закрытия ИПР",
                    ),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipr_for_employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Руководитель",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_ipr",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "goals",
                    models.ManyToManyField(
                        through="idps.GoalForIdp",
                        to="idps.goal",
                        verbose_name="Цели",
                    ),
                ),
            ],
            options={
                "verbose_name": "ИПР",
                "verbose_name_plural": "ИПРы",
                "ordering": ("created_at", "employee", "chief", "status"),
            },
        ),
        migrations.AddField(
            model_name="goalforidp",
            name="idp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_goals",
                to="idps.idp",
                verbose_name="ИПР",
            ),
        ),
        migrations.AddConstraint(
            model_name="idp",
            constraint=models.UniqueConstraint(
                fields=("title", "chief", "employee"),
                name="unique_ipr_for_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="idp",
            constraint=models.CheckConstraint(
                check=models.Q(("chief", models.F("employee")), _negated=True),
                name="self_follow",
            ),
        ),
    ]
