# Generated by Django 5.0.1 on 2024-01-31 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0005_alter_goal_status_alter_idp_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="idp",
            name="Возможно это не ваш сотрудник?",
        ),
        migrations.AddConstraint(
            model_name="idp",
            constraint=models.UniqueConstraint(
                fields=("title", "chief", "employee"),
                name="unique_idp_for_employee",
            ),
        ),
    ]
