# Generated by Django 5.0.1 on 2024-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0006_remove_idp_возможно_это_не_ваш_сотрудник__and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="idp",
            name="У сотрудника уже есть ИПР со статусом 'В работе'",
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(
                max_length=400, verbose_name="Текст комментария"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(
                max_length=100, verbose_name="Описание Цели"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=models.CharField(
                max_length=30, verbose_name="Название Цели"
            ),
        ),
        migrations.AlterField(
            model_name="idp",
            name="title",
            field=models.CharField(
                max_length=30, verbose_name="Наименование ИПР"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="text",
            field=models.TextField(max_length=30, verbose_name="Задача"),
        ),
    ]
