# Generated by Django 5.0.1 on 2024-02-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "idps",
            "0007_remove_idp_у_сотрудника_уже_есть_ипр_со_статусом_в_работе__and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="deadline",
            field=models.DateTimeField(
                db_index=True, verbose_name="Дата дедлайна"
            ),
        ),
    ]
