# Generated by Django 5.0.1 on 2024-02-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0008_alter_goal_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("В работе", "In progress"),
                    ("Выполнен", "Work done"),
                    ("Не выполнен", "Not done"),
                    ("Отменен", "Canceled"),
                ],
                default="В работе",
                max_length=11,
                verbose_name="Статус Цели",
            ),
        ),
        migrations.AlterField(
            model_name="idp",
            name="status",
            field=models.CharField(
                choices=[
                    ("В работе", "In progress"),
                    ("Выполнен", "Work done"),
                    ("Не выполнен", "Not done"),
                    ("Отменен", "Canceled"),
                ],
                default="В работе",
                max_length=11,
                verbose_name="Статус ИПР",
            ),
        ),
    ]
