# Generated by Django 5.0.1 on 2024-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_photos/",
                verbose_name="Фото",
            ),
        ),
    ]
