# Generated by Django 5.0.1 on 2024-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userrole_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fio",
            field=models.CharField(max_length=150, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title",
            field=models.CharField(max_length=30, verbose_name="Должность"),
        ),
    ]
