name: Check migrations

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  migrations:
    name: Check migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{secrets.DB_NAME_TEST}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER_TEST}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD_TEST}}
          POSTGRES_HOST: ${{secrets.DB_HOST_TEST}}
          POSTGRES_PORT: ${{secrets.DB_PORT_TEST}}
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Load Environment Variables
        run: |
          cp .env.example .env
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      -
        name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Create .env file
        run: |
          touch infra/.env
          echo DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY >> infra/.env
          echo DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS >> infra/.env
          echo CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS >> infra/.env
          echo POSTGRES_DB=$DB_NAME >> infra/.env
          echo POSTGRES_USER=$POSTGRES_USER >> infra/.env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> infra/.env
          echo POSTGRES_HOST=$DB_HOST >> infra/.env
          echo POSTGRES_PORT=$DB_PORT >> infra/.env
      -
        name: Run migrations
        run: python manage.py migrate
      -
        name: Check Migrations
        run: python manage.py makemigrations --check
