name: Check migrations

on:
  pull_request:
    branches:
      - develop
      - main

# env:
#   DJANGO_SECRET_KEY: testsecretkey
#   DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
#   CSRF_TRUSTED_ORIGINS: http://localhost
#   DB_ENGINE: django.db.backends.postgresql
#   DB_NAME: postgres
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: postgres
#   DB_HOST: localhost
#   DB_PORT: 5432

jobs:
  migrations:
    name: Check migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.DB_NAME}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_HOST: ${{env.DB_HOST}}
          POSTGRES_PORT: ${{env.DB_PORT}}
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Load Environment Variables
        run: |
          cp .env.example .env
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      -
        name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Create .env file
        run: |
          touch infra/.env
          echo DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY >> infra/.env
          echo DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS >> infra/.env
          echo CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS >> infra/.env
          echo POSTGRES_DB=$DB_NAME >> infra/.env
          echo POSTGRES_USER=$POSTGRES_USER >> infra/.env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> infra/.env
          echo POSTGRES_HOST=$DB_HOST >> infra/.env
          echo POSTGRES_PORT=$DB_PORT >> infra/.env
      -
        name: Run migrations
        run: python manage.py migrate
      -
        name: Check Migrations
        run: python manage.py makemigrations --check
